name: StevesBot
services:
  webhook:
    container_name: steves-bot-webhook
    image: stevanfreeborn/steves-bot:${WEBHOOK_VERSION}
    ports:
      - '34827:8080'
    restart: always
    environment:
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Information
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
      - YouTubeClientOptions__BaseUrl=${YOUTUBE_BASE_URL}
      - YouTubeClientOptions__ApiKey=${YOUTUBE_API_KEY}
      - SubscriptionOptions__CallbackUrl=${SUBSCRIPTION_CALLBACK_URL}
      - SubscriptionOptions__TopicUrl=${SUBSCRIPTION_TOPIC_URL}
      - PubSubClientOptions__BaseUrl=${PUBSUB_BASE_URL}
      - DiscordClientOptions__ApiUrl=${DISCORD_API_URL}
      - DiscordClientOptions__AppToken=${DISCORD_APP_TOKEN}
      - DiscordClientOptions__Intents=${DISCORD_INTENTS}
      - DiscordNotificationOptions__ChannelId=${DISCORD_NOTIFICATION_CHANNEL_ID}
      - DiscordNotificationOptions__MessageFormat="${DISCORD_NOTIFICATION_MESSAGE_FORMAT}"
      - SeqOptions__ServerUrl=${SEQ_SERVER_URL}
      - SeqOptions__ApiKeyHeader=${SEQ_API_KEY_HEADER}
      - SeqOptions__ApiKey=${SEQ_WEBHOOK_API_KEY}
      - DOTNET_ENVIRONMENT=Production
  worker:
    container_name: steves-bot-worker
    image: stevanfreeborn/steves-bot:${WORKER_VERSION}
    environment:
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Information
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
      - DiscordClientOptions__ApiUrl=${DISCORD_API_URL}
      - DiscordClientOptions__AppToken=${DISCORD_APP_TOKEN}
      - DiscordClientOptions__Intents=${DISCORD_INTENTS}
      - SeqOptions__ServerUrl=${SEQ_SERVER_URL}
      - SeqOptions__ApiKeyHeader=${SEQ_API_KEY_HEADER}
      - SeqOptions__ApiKey=${SEQ_WORKER_API_KEY}
      - DOTNET_ENVIRONMENT=Production
